### ISSUE TITLE
Angular depencies really needed?

### ISSUE THREAD

**Issue by vulvulune** [HNeukermans/adal-ts#13]
In the packages.json, there are a lot of @angular dev dependencies?

Is it really useful?

For me, this library should stay agnostic, and wrapper with app framework (Angular, Aurelia, ...) should be provided in another projects?

Not agree?

**Comment by HNeukermans** [comment]
Hey @vulvulune,

Indeed what you say is true. Fully agree. The libary does not depend on any angular dependencies. These are just remains of older code experiments. I forgot to remove them from the package.json though...

The wrapper idea you are talking about, is a good point. In the past, I already was thinking about something similar...

**Comment by HNeukermans** [comment]
the unused angular deps should now be removed from package.json
