### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by Him2021** [HNeukermans/adal-ts#6]
Do you have any examples that I can refer to integrate this in my project?

**Comment by HNeukermans** [comment]
Hi Him,

good to hear you are interested...
I will create a demo project with a live demo. I'm planning to implement this tonight. Maybe you can watch the project, so you are notified when things are ready.

**Comment by Him2021** [comment]
Thank you. I am watching the project now.

**Comment by HNeukermans** [comment]
created public adal-ts-consumer.
trying to get it up and running in azure the comming days...
